# Generated by Django 4.2.3 on 2023-07-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
